### ISSUE TITLE
undefined method 'config' for reality

### ISSUE THREAD

**Issue by gauravrakheja** [molybdenum-99/reality#69]
when I forked the repo and run rspec ., it throws undefined method for reality module with the following trace 

```
/home/gaurav/code/reality/spec/spec_helper.rb:17:in `<top (required)>': undefined method `configure' for Reality:Module (NoMethodError)
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `require'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `block in requires='
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `each'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `requires='
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `each'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/bin/rspec:23:in `load'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/bin/rspec:23:in `<main>'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
	from /home/gaurav/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by zverok** [comment]
Currently, specs are not supposed to work at all. 

They are all related to the previous version (preserved for historical reasons as a https://github.com/molybdenum-99/reality/tree/old-prototype-branch) and was NOT updated during "search & discovery" phase of creating the new version.

ETA for a polished release of the current prototype, with docs, specs & proper code quality is somewhere near the end of March.

(Of course, they should've been just cleaned up in this branch, but it is a dirty prototype, and most of things that "should've been done" are not :))
