### ISSUE TITLE
Error loading particular Wikidata item

### ISSUE THREAD

**Issue by ragesoss** [molybdenum-99/reality#71]
I'm hitting an error whenever I try to load Q408 (Australia).

```
Reality.wikidata.get('Q408')
 =>
Traceback (most recent call last):
       14: from /home/sage/.rvm/rubies/ruby-2.5.0/bin/irb:11:in `<main>'
       13: from (irb):34
       12: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/abstract/base.rb:9:in `get'
       11: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:16:in `observations_for'
       10: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:16:in `yield_self'
        9: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:62:in `process_entity'
        8: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:97:in `process_claims'
        7: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:97:in `map'
        6: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:97:in `each'
        5: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:97:in `block in process_claims'
        4: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:102:in `process_snaks'
        3: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:102:in `map'
        2: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata.rb:102:in `block in process_snaks'
        1: from /home/sage/.rvm/gems/ruby-2.5.0/gems/reality-0.1.0.alpha3/lib/reality/describers/wikidata/parsers.rb:11:in `snak'
NoMethodError (undefined method `fetch' for nil:NilClass)

**Comment by zverok** [comment]
Should be fixed in `master` now :) Do you want me to do a release or `master` is enough for your current goals?

**Comment by ragesoss** [comment]
Yeah, `master` should be fine. Thanks much!
