### ISSUE TITLE
Can't load 'miracles'

### ISSUE THREAD

**Issue by walterdavis** [molybdenum-99/reality#73]
I've installed reality 0.0.5, gem list reports that it is installed. The following happens when I try to follow the README:

```sh
waltd$ irb
2.4.6 :001 > require 'reality'
 => true 
2.4.6 :002 > require 'reality/miracles'
LoadError: cannot load such file -- reality/miracles
	from /Users/waltd/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:117:in `require'
	from /Users/waltd/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:117:in `require'
	from (irb):2
	from /Users/waltd/.rvm/rubies/ruby-2.4.6/bin/irb:11:in `<main>'
```
This is a well-working Ruby environment, where I've done a ton of Rails dev work without issue or error. Any suggestions to debug this?

**Comment by zverok** [comment]
Hey, unfortunately, Reality is a kind of weird state (huge refactoring/rewrite started, but then I don't have time to continue). Examples with "miracles" (in current README) work with prototype gem version `0.1.0.alpha3`, while 0.5.0's README is in the other branch: https://github.com/molybdenum-99/reality/tree/old-prototype-branch
